---
# tasks file for java

- name: Define java_packages
  set_fact:
    java_packages: "{{ __java_packages | list }}"
  when: java_packages is not defined

# Java installation.
- name: Ensure Java is installed
  apt:
    name: "{{ item }}"
    state: present
  with_items: "{{ java_packages | list }}"

# Environment setup.
- name: Set JAVA_HOME if configured
  template:
    src: java_home.sh.j2
    dest: /etc/profile.d/java_home.sh
    mode: 0644
  when: java_home is defined and java_home != ''